# ansible_host=# ansible_user=格式: ansible_password=IP
[linux_hosts]
172.21.15.1 ansible_host=172.21.15.1 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.2 ansible_host=172.21.15.2 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.3 ansible_host=172.21.15.3 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.5 ansible_host=172.21.15.5 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.6 ansible_host=172.21.15.6 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.7 ansible_host=172.21.15.7 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.8 ansible_host=172.21.15.8 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.9 ansible_host=172.21.15.9 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.10 ansible_host=172.21.15.10 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.12 ansible_host=172.21.15.12 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.13 ansible_host=172.21.15.13 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.14 ansible_host=172.21.15.14 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.15 ansible_host=172.21.15.15 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.16 ansible_host=172.21.15.16 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.17 ansible_host=172.21.15.17 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.18 ansible_host=172.21.15.18 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.20 ansible_host=172.21.15.20 ansible_user=android ansible_password=tinno123 ansible_ssh_timeout=10
172.21.15.22 ansible_host=172.21.15.22 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.23 ansible_host=172.21.15.23 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.24 ansible_host=172.21.15.24 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.25 ansible_host=172.21.15.25 ansible_user=android ansible_password=tinno123 ansible_ssh_timeout=10
172.21.15.26 ansible_host=172.21.15.26 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.27 ansible_host=172.21.15.27 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.28 ansible_host=172.21.15.28 ansible_user=android ansible_password=tinno123 ansible_ssh_timeout=10
172.21.15.29 ansible_host=172.21.15.29 ansible_user=android ansible_password=tinno123 ansible_ssh_timeout=10
172.21.15.32 ansible_host=172.21.15.32 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.33 ansible_host=172.21.15.33 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.34 ansible_host=172.21.15.34 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.35 ansible_host=172.21.15.35 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.36 ansible_host=172.21.15.36 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.15.37 ansible_host=172.21.15.37 ansible_user=android ansible_password=tinno123 ansible_ssh_timeout=10
172.21.15.38 ansible_host=172.21.15.38 ansible_user=android ansible_password=123 ansible_ssh_timeout=10
172.21.10.36 ansible_host=172.21.10.36 ansible_user=android ansible_password=123 ansible_ssh_timeout=10