# uncompyle6 version 3.9.3
# Python bytecode version base 3.7.0 (3394)
# Decompiled from: Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
# Embedded file name: modules\common\GlobalAttrs.py
"""
全局变量
"""
MICROSERVICE_SERVER = "10.204.124.214"
SCAN_MODE_AEE_TNE = 0
SCAN_MODE_AEE = 1
SCAN_MODE_TNE = 2
SCAN_MODE_FANS = 3
SCAN_MODE_USIC = 4
SCAN_MODE_PLATFORM = 5
SCAN_MODE_DAILY = 6
SCAN_MODE_JENKINS = 7
SCAN_MODE_HWASAN = 8
SCAN_MODE_MTBF_PLATFORM = 9
SCAN_MODE_STUCK_LOGO = 10
SCAN_MODE_CAMERA_PLATFORM = 11
SCAN_MODE_VIDEO_PLATFORM = 12
SCAN_MODE_SUNMAO_PLATFORM = 13
SCAN_MODE_FREEZE = 14
SCAN_MODE_HWASAN_PLATFORM = 15
SCAN_MODE_FUZZ = 16
SCAN_MODE_FUZZ_PLATFORM = 17
SCAN_MODE_OTA_DAILY = 18
SCAN_MODE_INDEPENDENT = 19
SCAN_MODE_DAEMON_CRASH = 20
SCAN_MODE_SUBSYSTEM_CRASH = 21
SCAN_MODE_UPLOAD_TNE = 22
SCAN_MODE_MERGE = 99
SCAN_MODE_DICT = {SCAN_MODE_AEE_TNE: "Aee-Tne", 
 SCAN_MODE_AEE: "Aee", 
 SCAN_MODE_TNE: "Tne", 
 SCAN_MODE_FANS: "Fans", 
 SCAN_MODE_USIC: "Usic", 
 SCAN_MODE_PLATFORM: "Platform", 
 SCAN_MODE_DAILY: "Daily", 
 SCAN_MODE_JENKINS: "Jenkins", 
 SCAN_MODE_HWASAN: "HWASan", 
 SCAN_MODE_HWASAN_PLATFORM: "HWASanPlatform", 
 SCAN_MODE_MTBF_PLATFORM: "MTBF", 
 SCAN_MODE_STUCK_LOGO: "StuckLogo", 
 SCAN_MODE_CAMERA_PLATFORM: "CameraPlatform", 
 SCAN_MODE_VIDEO_PLATFORM: "VideoPlatform", 
 SCAN_MODE_SUNMAO_PLATFORM: "SunMaoPlatform", 
 SCAN_MODE_FREEZE: "Freeze", 
 SCAN_MODE_MERGE: "Merge", 
 SCAN_MODE_FUZZ: "Fuzz", 
 SCAN_MODE_FUZZ_PLATFORM: "FuzzPlatform", 
 SCAN_MODE_OTA_DAILY: "OTADaily", 
 SCAN_MODE_INDEPENDENT: "Independent", 
 SCAN_MODE_DAEMON_CRASH: "DaemonCrash", 
 SCAN_MODE_SUBSYSTEM_CRASH: "SubsystemCrash", 
 SCAN_MODE_UPLOAD_TNE: "UploadTne"}
EXIT_CODE_INVALID_SCAN_DIR = -1
EXIT_CODE_INVALID_ENV = -2
EXIT_CODE_INVALID_SCAN_MODE = -3
FEISHU_POST_HEADERS = {"Content-Type": "application/json"}
FEISHU_ROBOT_URL = "https://open.feishu.cn/open-apis/bot/v2/hook/53957243-03ae-407f-99cf-be6136997991"
FEISHU_ROBOT_PLATFORM_MONKEY_URL = "https://open.feishu.cn/open-apis/bot/v2/hook/5b536549-8b64-422a-b129-6ce591d213d9"
RECOGNIZE_LIB_VERSION = "解析库版本：recognizeexception 1.0.8"

# okay decompiling extracted_pyz_modules\modules\common\GlobalAttrs.pyc
